import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gradient-to-br from-yellow-200 to-rose-300 overflow-hidden">
        <div className="container mx-auto">
          <main className="w-screen h-screen sm:w-auto bg-white/30 backdrop-blur-md rounded-xl py-8 px-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
